### ISSUE TITLE
Form and IS_DATE(format) mistatch

### ISSUE THREAD

**Issue by digver** [web2py/py4web#189]
FormStyleDefault renders date fields as type="text" rather than type="date" which results in the date-picker not being displayed.  Adding a "date" entry to FormStyleDefault and FormStyleBulma solves the problem.

```
--- form.py	2020-05-04 23:52:33.000000000 -0400
+++ form-date.py	2020-05-09 18:15:40.919309885 -0400
@@ -50,6 +50,9 @@
             control = field.widget(table, value)
         elif field.type == "text":
             control = TEXTAREA(value or "", _id=input_id, _name=field.name)
+        elif field.type == "date":
+            control = INPUT(_value=value, _type="date", _id=input_id, _name=field.name)
+        
         elif field.type == "boolean":
             control = INPUT(
                 _type="checkbox",
@@ -142,6 +145,7 @@
         "submit": "button",
         "input": "input",
         "input[type=text]": "input",
+        "input[type=date]": "input",
         "input[type=radio]": "radio",
         "input[type=checkbox]": "checkbox",
         "input[type=submit]": "button",

```

**Comment by jpsteil** [comment]
I've implemented this fix on my local version of py4web but am still having issues.  What I'm seeing is that adding this fix implements the HTML5 date control.  But, then this breaks the validator because from what I can tell, the HTML5 date control always stores the date in proper format for the locale used by your browser.

With web2py you can pass different date formats to the requires=IS_DATE() validator which set the required format for the value in the control.  Since the HTML5 date control always uses your locale, this will no longer work.

I don't have a fix for this unfortunately.  I'm not sure what the intention of the team is for this functionality.  Are we to use the HTML5 date control or do you intent to implement a custom control like was done in web2py?

**Comment by jpsteil** [comment]
I just looked at Flask-WTF to see how they handle this.  It appears as though they have a different field type for HTML5 dates.  I wonder if a new validator that is HTML5 specific that doesn't take the format as an argument is the answer.

**Comment by mdipierro** [comment]
Can this be closed?

**Comment by jpsteil** [comment]
Yes

**Comment by digver** [comment]
Yes! I thought that happened a while ago.

Sent from ProtonMail mobile

-------- Original Message --------
