### ISSUE TITLE
Add syntax useful for widgets: Allow  a.x instead requiring a['x'].

### ISSUE THREAD

**Issue by tomcam** [web2py/py4web#332]
From this week's chat and the thread at https://groups.google.com/d/msg/py4web/ITw3OLyT1iA/tTXcetDuBwAJ:

About widgets. I think we have the functionality that we need. I think if people what custom widgets they can make them already. I only suggested that perhaps we should support an alterantive syntax to a.x instead of a['x'].

**Comment by valq7711** [comment]
@mdipierro 

I spent some tests and here is the conclusions:
1.   functions of built-in objects (like `dict`) is highly optimized and any overwriting them (even using simple lambda) causes impact on performance
2. In case of web2py `Storage`,  `__getattr__` is the main evil - `obj.a` is about 2 times slower than  `obj['a']`
Also, as far as I understand, attribute access is slow by design as it has some complex business logic under the hood.
3. Good news:  there is `types.SimpleNamespace` with the same fast access to attributes as dict to items
Bad news:  it hasn't   `__getitem__/__setitem__`.  

So here's a trade-off with almost no performance penalty.

```python
'''
obj = NS_()
obj.a = 1   # as fast as dict
obj._['a'] = 1  # -5% 
obj['a'] = 1   # -20...30% 

Just use obj._[...] in loops to avoid performance down
+ since obj._ is just a dict you can always somevar = obj._ and use it to get full speed!

'''

class NS_(types.SimpleNamespace):
        __getitem__ = types.SimpleNamespace.__getattribute__ # -20...30%
        __setitem__ = types.SimpleNamespace.__setattribute__  # -20...30%
        _ = None
        def __init__(self, **kw):
            super().__init__(**kw)
            self._ = self.__dict__
```

**Comment by mdipierro** [comment]
Interesting!
