### ISSUE TITLE
api_jwt monkey patch needed (or py4web code updated)

### ISSUE THREAD

**Issue by sp1d3rx** [web2py/py4web#494]
After fixing line 81 of factories (see other issue) I ran into another issue with clicking 'like'. It would give me 

`
    'It is required that you pass in a value for the "algorithms" argument when calling decode().'
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().
`

What I did was patch jwt.api_jwt.py with this in decode_complete (at the very beginning):
`
        if algorithms is None:
            algorithms = get_default_algorithms()
`
Perhaps Py4Web should get the default algorithms and pass that in when calling jwt.api_jwt.py.

**Comment by Kkeller83** [comment]
I think we just need to pass the right algorithms to pyjwt and better not monkey patch pyjwt. that will become unmaintainable. I think its best if we state the algo. that we use when encoding and decoding always as a best practice. It seems it is now enforced anyway. The algo that needs to be passed is HS256. Will try to get a PR going to test this. Could you help me test this? The line should probably be: return (URL(path), jwt.encode(data, Session.SECRET, algorithms=["HS256"]).decode() and jwt.decode(json.loads(request.body.read()), Session.SECRET,algorithms=["HS256"])

**Comment by sp1d3rx** [comment]
sure, but the '.decode()' won't work - its a string object returned not a bytes.

**Comment by agavgavi** [comment]
The cause behind this issue is that pyJWT completely rewrote their framework between versions 1.7.X (py4web's minimum supported version) and 2.0. In 1.7.X, the method of decoding that currently exists in py4web works perfectly, but if you're using any later version it will break.

This is a discussion for the team to see if it's important to update everywhere pyJWT is used and set a new minimum version of 2.0, or to set the requirements.txt to REQUIRE 1.7.X

**Comment by mdipierro** [comment]
this has been fixed but you all need to upgrade to the new required 2.0.1
