### ISSUE TITLE
Error in Form() generating the html of the field labels when there is no table

### ISSUE THREAD

**Issue by cdb88** [web2py/py4web#728]
The for attribute of <label> is incorrect,

Should be for="**no_table**_c_accept" but it renders like this for="**none**_c_accept"

 ```
   form = Form(
        table=[
            Field('c_accept', 'boolean', label='Acepto')
        ],
        keep_values=True,
    )

<span class="">
    <input class="" id="no_table_c_accept" name="c_accept" type="checkbox" value="ON">
</span>
<label class="" for="no_table_c_accept" style="display: inline !important"> Acepto</label>

Correct:

<span class="">
    <input class="" id="no_table_c_accept" name="c_accept" type="checkbox" value="ON">
</span>
<label class="" for="none_c_accept" style="display: inline !important"> Acepto</label>

```
I think the solution is in line 346 of the Form.py file
```
- input_id = "%s_%s" % (field.tablename, field.name)
+ input_id = to_id(field)
```

**Comment by jpsteil** [comment]
I think the fix is actually in line 719 in form.py

form_name = form_name or 'none'

should be

form_name = form_name or 'no_table'

Can you submit a PR?

If not, I'll try to get time today.

-Jim

**Comment by cdb88** [comment]
Thank you very much for responding so quickly.

I have never done a PR :-( sorry, I promise to learn how to do it.

I have tried your solution, but it doesn't work well.

With the example above it works fine, but if I use the parameter form_name="form_1" it doesn't work.

The id attribute of <input> always starts with "no_table" even when form_name is used.

The for attribute of <label> does not have the same behavior.

I guess we'll have to look at it more slowly, to be consistent with the name of the table.

**Comment by jpsteil** [comment]
I'll check it again after lunch.

Jim

**Comment by jpsteil** [comment]
After looking further I think we should wait until Massimo has a chance to
look at it to make sure all is in alignment.

I'm not sure the intent of the form_name parameter and how 'no_table'
should be set.

Another fix I tried that seems to work is first undo my first suggestion
and then  on line 721, change

field.tablename = getattr(field, "tablename", form_name)

to

field.tablename = getattr(field, "tablename", "no_table")

I say that because the function

def to_id(field):
    """get an identified for a field"""
    return "%s_%s" % (getattr(field, "_tablename", "no_table"), field.name)

Seems to set that id to 'no_table' regardless of the formname passed in.

Does that seem to work for you?

-Jim

**Comment by cdb88** [comment]
This solution seems to work fine for me.
