### ISSUE TITLE
web2py 2.23.0 403 error when packing applications 

### ISSUE THREAD

**Issue by DavidiBeMe** [web2py/py4web#771]
I just did a test on my Windows PC with web2py v. 2.23.0 out of the box and I got a 403 error when packing any application.

I found where this is occurring (out of the box run, no mods):

C:\Users\myuser\web2py_2.23.0\web2py\applications\admin\controllers\default.py:
def safe_open(a, b):
    if (DEMO_MODE or is_gae) and ('w' in b or 'a' in b):
        class tmp:

            def write(self, data):
                pass

            def close(self):
                pass
        return tmp()

    a_for_check = os.path.abspath(os.path.normpath(a))
    web2py_apps_root = os.path.abspath(up(request.folder))

    if not a_for_check.startswith(web2py_apps_root):
        raise HTTP(403) 

The values of the variables at the time of the error :
web2py_apps_root = 'C:\\Users\\myuser\\web2py_2.23.0\\web2py\\applications'
a_for_check =  'C:\\Users\\myuser\\web2py_2.23.0\\web2py\\deposit\\web2py.app.403_test.w2p'

**Comment by mdipierro** [comment]
This is a but introduced very recently. I will fix it in the next 1-2 days
and release a new version.Thanks for letting me know.

**Comment by DavidiBeMe** [comment]
Just so you know, I entered it as an issue for web2py in github as well.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by spametki** [comment]
Hi! I had the same issue with 2.23.1-stable+timestamp.2023.01.31.08.01.46 on a Win 10 Education OS

Looking at the code in admin/default.py pointed by DavidiBeMe, the problem seems to be about the safe_open function.

The filepath in a_for_check looks for "deposit" folder, which contains the file to stream, but the web2py_apps_root is at ../applications.  The function checks wheter the input file folder is contained by ../applications, and raises HTTP 403 Forbidden, because the condition is not satisfied

**Comment by mdipierro** [comment]
Thank you. I have overlooked this issue. I posted a fix and released web2py
2.24.1
